let photos = [
    {
        img: '2wCEAAkGBxMTEhUSExMVFRUWFRYZFhUYFxgVFRcVGRgXGBYWGBYYHSggGBolGxgYITEiJikrLi4uGR8zODMtNygtLysBCgoKDg0OGhAQFy0fHyUtLS0tLS0tLS0tLS0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf'
    },
    {
        img: '2wCEAAkGBxMTEhUSExMVFRUWFRYZFhUYFxgVFRcVGRgXGBYWGBYYHSggGBolGxgYITEiJikrLi4uGR8zODMtNygtLysBCgoKDg0OGhAQFy0fHyUtLS0tLS0tLS0tLS0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf'
    },
    {
        img: '2wCEAAkGBxMTEhUSExMVFRUWFRYZFhUYFxgVFRcVGRgXGBYWGBYYHSggGBolGxgYITEiJikrLi4uGR8zODMtNygtLysBCgoKDg0OGhAQFy0fHyUtLS0tLS0tLS0tLS0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf'
    },
    {
        img: '2wCEAAkGBxMTEhUSExMVFRUWFRYZFhUYFxgVFRcVGRgXGBYWGBYYHSggGBolGxgYITEiJikrLi4uGR8zODMtNygtLysBCgoKDg0OGhAQFy0fHyUtLS0tLS0tLS0tLS0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf'
    },
    {
        img: '2wCEAAkGBxMTEhUSExMVFRUWFRYZFhUYFxgVFRcVGRgXGBYWGBYYHSggGBolGxgYITEiJikrLi4uGR8zODMtNygtLysBCgoKDg0OGhAQFy0fHyUtLS0tLS0tLS0tLS0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf'
    }
]

export default photos;